name: solufacil-api
region: nyc
services:
  - name: api
    environment_slug: node-js
    github:
      repo: DevLugo/solufacil-api
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pnpm build && pnpm deploy:migrate
    run_command: node dist/server.js
    http_port: 4000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_CLOUD_NAME
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        scope: RUN_TIME
        type: SECRET
